<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Day_txtDay</name>
   <tag></tag>
   <elementGuidId>6c54b81b-9836-4945-85ca-e5dab03beece</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='txtDay']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;txtDay&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84a73928-5d3a-44c3-9e23-47c4365fca56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fb0784c5-2dfc-40f9-8d3d-2edca81b7757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDay</value>
      <webElementGuid>696f5697-b3df-4b09-8649-c1620fe4078a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/form[1]/table[1]/tbody[1]/tr[1]/td[2]/input[1]</value>
      <webElementGuid>0616c162-a022-4093-a19b-7d46154474e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='txtDay']</value>
      <webElementGuid>c86d11a6-3914-4e6d-b8fb-f78d73448c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day'])[1]/following::input[1]</value>
      <webElementGuid>9a885835-d37a-479c-b2fd-bd53b9ca9e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Time Checker'])[2]/following::input[1]</value>
      <webElementGuid>857c1031-a368-4d6f-9f9d-8633215e4ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Month'])[1]/preceding::input[1]</value>
      <webElementGuid>7e02164a-7c8f-443e-9fb1-4e8d2de6597e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year'])[1]/preceding::input[2]</value>
      <webElementGuid>f16f39c4-96ce-4239-9873-3ff461ac3e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7cbff7bb-e646-4468-bdc7-acf612dc4d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txtDay']</value>
      <webElementGuid>fed19c8e-3cc3-41ee-a312-8578cadac63a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
